name: Rust

on:
  push:
    branches: [ main, fix-dependencies ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add thumbv7em-none-eabihf
    - name: Install flip-link
      run: cargo install flip-link
    - name: Build
      run: cargo build --verbose
